name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push request event for the master branch
  push:    
    branches: [master]

jobs:
  deploy:
    # Our previously created self-hosted runner
    runs-on: self-hosted

    # A sequence of tasks that will execute as part of the job
    steps:

      - name: Install dependencies
        run: dotnet restore


      # We will output publish files to the folder we previously created
      - name: Publish
        run: dotnet publish -c Release -o /var/www/m3u8-proxy --runtime linux-x64 --self-contained true
        
      - name: Restart the app
        run: |
          export XDG_RUNTIME_DIR=/run/user/$(id -u)
          systemctl --user restart m3u8-proxy.service  
